### ISSUE TITLE
Fatal error: Uncaught Error: Class "Symfony\Component\EventDispatcher\Event" not found 

### ISSUE THREAD

**Issue by k-webdesign** [netzmacht/contao-leaflet-maps#129]
Hi David, 

ich versuch das grad unter Contao 4.13 zu installieren 
```"netzmacht/contao-leaflet-maps": "3.0",```

``` 
Stack trace:
#0 /Users/kim/develop/mamp/spitzl/contao-4-9-x/vendor/composer/ClassLoader.php(571): include()
#1 /Users/kim/develop/mamp/spitzl/contao-4-9-x/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/Users/kim/deve...')
#2 /Users/kim/develop/mamp/spitzl/contao-4-9-x/vendor/netzmacht/contao-leaflet-maps/src/Listener/HashSubscriber.php(31): Composer\Autoload\ClassLoader->loadClass('Netzmacht\\Conta...')
#3 /Users/kim/develop/mamp/spitzl/contao-4-9-x/vendor/symfony/event-dispatcher/DependencyInjection/RegisterListenersPass.php(232): Netzmacht\Contao\Leaflet\Listener\HashSubscriber::getSubscribedEvents()
#4 /Users/kim/develop/mamp/spitzl/contao-4-9-x/vendor/symfony/event-dispatcher/EventDispatcher.php(183): Symfony\Component\EventDispatcher\DependencyInjection\ExtractingEventDispatcher::getSubscribedEvents()
#5 /Users/kim/develop/mamp/spitzl/contao-4-9-x/vendor/symfony/event-dispatcher/DependencyInjection/RegisterListenersPass.php(174): Symfony\Component\EventDispatcher\EventDispatcher->addSubscriber(Object(Symfony\Component\EventDispatcher\DependencyInjection\ExtractingEventDispatcher))
#6 /Users/kim/develop/mamp/spitzl/contao-4-9-x/vendor/symfony/dependency-injection/Compiler/Compiler.php(82): Symfony\Component\EventDispatcher\DependencyInjection\RegisterListenersPass->process(Object(Contao\ManagerPlugin\Config\ContainerBuilder))
#7 /Users/kim/develop/mamp/spitzl/contao-4-9-x/vendor/symfony/dependency-injection/ContainerBuilder.php(757): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Contao\ManagerPlugin\Config\ContainerBuilder))
#8 /Users/kim/develop/mamp/spitzl/contao-4-9-x/vendor/symfony/http-kernel/Kernel.php(546): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#9 /Users/kim/develop/mamp/spitzl/contao-4-9-x/vendor/contao/manager-bundle/src/HttpKernel/ContaoKernel.php(290): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#10 /Users/kim/develop/mamp/spitzl/contao-4-9-x/vendor/symfony/http-kernel/Kernel.php(787): Contao\ManagerBundle\HttpKernel\ContaoKernel->initializeContainer()
#11 /Users/kim/develop/mamp/spitzl/contao-4-9-x/vendor/symfony/http-kernel/Kernel.php(128): Symfony\Component\HttpKernel\Kernel->preBoot()
#12 /Users/kim/develop/mamp/spitzl/contao-4-9-x/vendor/symfony/framework-bundle/Console/Application.php(168): Symfony\Component\HttpKernel\Kernel->boot()
#13 /Users/kim/develop/mamp/spitzl/contao-4-9-x/vendor/symfony/framework-bundle/Console/Application.php(74): Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands()
#14 /Users/kim/develop/mamp/spitzl/contao-4-9-x/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /Users/kim/develop/mamp/spitzl/contao-4-9-x/vendor/contao/manager-bundle/bin/contao-setup(44): Symfony\Component\Console\Application->run()
#16 /Users/kim/develop/mamp/spitzl/contao-4-9-x/vendor/bin/contao-setup(120): include('/Users/kim/deve...')
#17 {main}
  thrown in /Users/kim/develop/mamp/spitzl/contao-4-9-x/vendor/netzmacht/contao-leaflet-maps/src/Event/GetHashEvent.php on line 22
Script @php vendor/bin/contao-setup --ansi handling the post-update-cmd event returned with error code 255
```

**Comment by k-webdesign** [comment]
Sorry, mit ``` "^3.0" ``` gehts
