### ISSUE TITLE
Cannot create map - Contao 3.5, Leaflet-maps 2.0.0-beta2

### ISSUE THREAD

**Issue by taleteller** [netzmacht/contao-leaflet-maps#42]
Trying to add a map on a brand new installed netzmacht/contao-leaflet-maps 2.0.0-beta2 throws me this error:

```
Fatal error: Uncaught exception Exception with message Query error: Column 'cacheLifeTime' cannot be null (INSERT INTO tl_leaflet_map (zoom, adjustZoomExtra, dragging, touchZoom, scrollWheelZoom, doubleClickZoom, boxZoom, tap, trackResize, bounceAtZoomLimits, closeOnClick, keyboard, keyboardPanOffset, keyboardZoomOffset, zoomControl, adjustBounds, dynamicLoad, locate, locateWatch, locateTimeout, locateMaximumAge, enableHighAccuracy, cache, cacheLifeTime, tstamp) VALUES ('', 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 80, 1, 1, 0, 0, 0, 0, NULL, NULL, 0, 0, NULL, 0)) thrown in system/modules/core/library/Contao/Database/Statement.php on line 295

#0 system/modules/core/library/Contao/Database/Statement.php(264): Contao\Database\Statement->query()
#1 system/modules/core/drivers/DC_Table.php(689): Contao\Database\Statement->execute()
#2 system/modules/core/classes/Backend.php(650): Contao\DC_Table->create()
#3 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('leaflet_map')
#4 contao/main.php(20): Contao\BackendMain->run()
#5 {main}
```
Also on the bottom of every backend page i get this:

```
Fatal error: Uncaught exception 'Exception' with message 'Invalid connection resource' in /var/customers/webs/moarhof/system/modules/core/library/Contao/Database/Statement.php:92
Stack trace:
#0 /var/customers/webs/moarhof/system/modules/core/library/Contao/Database/Mysql.php(355): Contao\Database\Statement->__construct(Resource id #2, false)
#1 /var/customers/webs/moarhof/system/modules/core/library/Contao/Database.php(181): Contao\Database\Mysql->createStatement(Resource id #2, false)
#2 /var/customers/webs/moarhof/system/modules/core/classes/BackendUser.php(163): Contao\Database->prepare('UPDATE tl_user ...')
#3 [internal function]: Contao\BackendUser->__destruct()
#4 {main}
  thrown in /var/customers/webs/moarhof/system/modules/core/library/Contao/Database/Statement.php on line 92
```

**Comment by dmolineus** [comment]
First issue is fixed in 2.0.0-beta3. Can't reproduce the second issue. Are there any other extensions active? I opened another issue for that. Would be great if you could give any feedback there #43
